[package]
name = "apic"
version = "0.1.0"
edition = "2024"

[dependencies]
x86_64 = "0.15.2"
hal = { path = "../hal" }
idt = { path = "../idt" }
keyboard = { path = "../keyboard" }
[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
